/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pbt_rh_ar_LanguageInfo */

#ifndef _Included_org_pbt_rh_ar_LanguageInfo
#define _Included_org_pbt_rh_ar_LanguageInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_pbt_rh_ar_RHVoiceException */

#ifndef _Included_org_pbt_rh_ar_RHVoiceException
#define _Included_org_pbt_rh_ar_RHVoiceException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_pbt_rh_ar_RHVoiceException_serialVersionUID
#define org_pbt_rh_ar_RHVoiceException_serialVersionUID -3042686055658047285LL
#undef org_pbt_rh_ar_RHVoiceException_serialVersionUID
#define org_pbt_rh_ar_RHVoiceException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_pbt_rh_ar_SynthesisParameters */

#ifndef _Included_org_pbt_rh_ar_SynthesisParameters
#define _Included_org_pbt_rh_ar_SynthesisParameters
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_pbt_rh_ar_TTSClient */

#ifndef _Included_org_pbt_rh_ar_TTSClient
#define _Included_org_pbt_rh_ar_TTSClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_pbt_rh_ar_TTSEngine */

#ifndef _Included_org_pbt_rh_ar_TTSEngine
#define _Included_org_pbt_rh_ar_TTSEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pbt_rh_ar_TTSEngine
 * Method:    onClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pbt_rh_ar_TTSEngine_onClassInit
  (JNIEnv *, jclass);

/*
 * Class:     org_pbt_rh_ar_TTSEngine
 * Method:    onInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lorg/pbt/rh/ar/Logger)V
 */
JNIEXPORT void JNICALL Java_org_pbt_rh_ar_TTSEngine_onInit
(JNIEnv *, jobject, jstring, jstring, jobjectArray, jstring, jobject);

/*
 * Class:     org_pbt_rh_ar_TTSEngine
 * Method:    onShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pbt_rh_ar_TTSEngine_onShutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_pbt_rh_ar_TTSEngine
 * Method:    doGetVoices
 * Signature: ()[Lorg/pbt/rh/ar/VoiceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_org_pbt_rh_ar_TTSEngine_doGetVoices
  (JNIEnv *, jobject);

/*
 * Class:     org_pbt_rh_ar_TTSEngine
 * Method:    doSpeak
 * Signature: (Ljava/lang/String;Lorg/pbt/rh/ar/SynthesisParameters;Lorg/pbt/rh/ar/TTSClient;)V
 */
JNIEXPORT void JNICALL Java_org_pbt_rh_ar_TTSEngine_doSpeak
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     org_pbt_rh_ar_TTSEngine
 * Method:    doConfigure
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pbt_rh_ar_TTSEngine_doConfigure
(JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jstring JNICALL Java_org_pbt_rh_ar_TTSEngine_doGetCachedPackageDir
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_org_pbt_rh_ar_TTSEngine_doGetPackageDirFromServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_pbt_rh_ar_VoiceInfo */

#ifndef _Included_org_pbt_rh_ar_VoiceInfo
#define _Included_org_pbt_rh_ar_VoiceInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
